steps:
  # 1. Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/music-play-repo/music-play-app'
      - '.'

  # 2. Artifact Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/music-play-repo/music-play-app'

  # 3. Cloud Run にデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'music-play-app'
      - '--image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/music-play-repo/music-play-app'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/music-play-repo/music-play-app'  # 変更

options:
  logging: CLOUD_LOGGING_ONLY
